import aiofiles
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

DOWNLOADS = Path("downloads")
DOWNLOADS.mkdir(exist_ok=True)


async def handle_create_python() -> Dict[str, Any]:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"lucia_python_{timestamp}.py"
    filepath = DOWNLOADS / filename
    python_code = f'''#!/usr/bin/env python3
"""Generated by Lucia (cleaned)
Timestamp: {datetime.now().isoformat()}
"""

if __name__ == "__main__":
    print("Hello from Lucia cleaned server")
'''
    async with aiofiles.open(str(filepath), 'w', encoding='utf-8') as f:
        await f.write(python_code)
    return {"ok": True, "filename": filename}


async def handle_create_html() -> Dict[str, Any]:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"lucia_webpage_{timestamp}.html"
    filepath = DOWNLOADS / filename
    html_code = """<!DOCTYPE html>
<html>
  <head><meta charset="utf-8"><title>Lucia Page</title></head>
  <body><h1>Lucia Generated Page</h1></body>
</html>
"""
    async with aiofiles.open(str(filepath), 'w', encoding='utf-8') as f:
        await f.write(html_code)
    return {"ok": True, "filename": filename}


async def handle_create_text() -> Dict[str, Any]:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"lucia_notes_{timestamp}.txt"
    filepath = DOWNLOADS / filename
    text = f"Lucia notes\nGenerated: {datetime.now().isoformat()}\n"
    async with aiofiles.open(str(filepath), 'w', encoding='utf-8') as f:
        await f.write(text)
    return {"ok": True, "filename": filename}


async def handle_list_files() -> Dict[str, Any]:
    files = []
    for p in DOWNLOADS.iterdir():
        if p.is_file():
            stat = p.stat()
            files.append({"name": p.name, "size": stat.st_size, "modified": datetime.fromtimestamp(stat.st_mtime).isoformat()})
    return {"ok": True, "files": files}


async def handle_download(filename: str) -> Dict[str, Any]:
    filepath = DOWNLOADS / filename
    if filepath.exists():
        return {"ok": True, "path": str(filepath)}
    return {"ok": False, "message": "파일을 찾을 수 없습니다"}


async def handle_delete(filename: str) -> Dict[str, Any]:
    filepath = DOWNLOADS / filename
    if filepath.exists():
        try:
            filepath.unlink()
            return {"ok": True}
        except Exception as e:
            return {"ok": False, "message": str(e)}
    return {"ok": False, "message": "파일을 찾을 수 없습니다"}
